@"
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
android.enableJetifier=true
android.useAndroidX=true
android.injected.testOnly=false
"@ | Out-File -FilePath android\gradle.properties -Encoding utf8
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
